language: scala

jdk:
  - openjdk8

script:
  - sbt compile

# From https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
